[project]
name = "astro-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "arviz>=1.2.0",
    "astropy>=8.0.1",
    "corner>=2.3.0",
    "emcee>=3.1.6",
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.1",
    "matplotlib>=3.11.0",
    "numpy>=2.5.1",
    "pandas>=3.0.3",
    "scipy>=1.18.0",
    "tqdm>=4.69.0",
]

[dependency-groups]
dev = [
    "ipython>=9.15.0",
    "mypy>=2.3.0",
    "pytest>=9.1.1",
    "ruff>=0.15.21",
]
